CREATE TABLE logins (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    user VARCHAR NOT NULL UNIQUE,
    pass VARCHAR NOT NULL
);

CREATE TABLE artists (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name ntext NOT NULL,    
    mbid VARCHAR
);

CREATE TABLE apis (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    sitename VARCHAR NOT NULL
);

CREATE TABLE apiinfo (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    api_id INTEGER NOT NULL,
    key VARCHAR NOT NULL UNIQUE,
    value VARCHAR NOT NULL UNIQUE,
    FOREIGN KEY (api_id) REFERENCES apis (id)
);

CREATE TABLE artistdata (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    artist_id INTEGER NOT NULL,
    api_id INTEGER NOT NULL,
    key VARCHAR NOT NULL,
    value VARCHAR NOT NULL,
    FOREIGN KEY (artist_id) REFERENCES artists (id),
    FOREIGN KEY (api_id) REFERENCES apis (id)
);
